providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "libffi",
  "openssl",
  "zlib",
  "libjpeg",
  "freetype",
  "lcms2",
  "libwebp",
  "tcl",
  "tk",
  "libpng",
  "libxml2",
  "pango",
  "cairo"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]


