[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "libffi",
  "openssl",
  "zlib",
  "libjpeg",
  "freetype",
  "lcms2",
  "libwebp",
  "tcl",
  "tk",
  "libpng",
  "wkhtmltopdf"
]

[phases.setup_apt]
aptPkgs = [
  "fonts-noto-core",
  "fonts-noto-ui-core",
  "fonts-noto-sans-devanagari"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]


